digest_subject = "Code Review Daily Digest"
sender = "a@b.com"
project = "mediawiki/extensions/MobileFrontend"
recipients = "yourmail@mail.com"
username = "username"
password = "***"
smtp = "smtp.x.com"
